remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: dark

locale: en-US
title: Stand of Giants Games
subtitle: We make games, occasionally
name: Zara Sabre
description: >
  A site for the stand of giants game development group.
url: https://zipcodeman.name
logo: /assets/images/logo.png
show_date: true
atom_feed:
  path: https://zipcodeman.name/podfics.rss
twitter:
  username: _zipcodeman
analytics:
  provider: google-gtag
  google:
    tracking_id: G-6N8Q0D5EZD

author:
  name: Zara Sabre
  avatar: /assets/images/pfp.png
  bio: A potato person who makes things, occasionally
  location: Earth
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/_zipcodeman
    - label: itch.io
      icon: fab fas fa-gamepad
      url: https://zipcodeman.itch.io
    - label: Ao3
      icon: fab fas fa-book
      url: https://archiveofourown.org/users/zipcodeman
github:
  is_project_page: false

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
